# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=155, unique=True, verbose_name='Name'),
        ),
    ]
