# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 11:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2017, 3, 12, 12, 42, 23, 675507))),
                ('slug', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=155)),
                ('subtitle', models.CharField(max_length=155)),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=155)),
                ('thumbnail', models.FilePathField(match='.+(.png|.jpg)$', path='static\\uploads')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category')),
            ],
        ),
    ]
