# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='posts', to='blogs.Blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FilePathField(match='.+(.png|.jpg)$', path='static/uploads'),
        ),
    ]
