# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20170319_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FilePathField(blank=True, default=None, match='.+(.png|.jpg)$', null=True, path='static/uploads'),
        ),
    ]
